# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
import numpy as np
a = np.array([1,2,3,4,5,6]).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [11]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10).reshape(2,5)
final = np.vstack((arr1,arr2))
final

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [15]:
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)
final = np.hstack((a,b))
final

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
flat_array = arr.flatten()
flat_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [23]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
arr2 = arr.reshape((16,))
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [31]:
arr = np.arange(15)
print('1d Array',arr)
print('==============================')
arr2d = arr.reshape((3,5))
print('Array2d',arr2d)

1d Array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Array2d [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [56]:
import random
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

## Question:8

### Create 5x6 an array and find the mean?

In [58]:
Arr = np.arange(30).reshape(5,6)
Arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
print('Mean of Arr: ', np.mean(Arr))

Mean of Arr:  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [60]:
print('Standard deviation of Q8: ', np.std(Arr))

Standard deviation of Q8:  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [61]:
print('Median Of Q8: ', np.median(Arr))

Median Of Q8:  14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [62]:
np.transpose(Arr)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [73]:
Arr1 = np.arange(16).reshape(4,4)
print('4x4 Array:\n\n', Arr1)
print('======================')
x = np.diagonal(Arr1)
print('Diagonal Element: ',x)
print('======================')
print('Sum of diagonal elements is:',sum(x))

4x4 Array:

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Diagonal Element:  [ 0  5 10 15]
Sum of diagonal elements is: 30


## Question:13

### Find the determinant of the previous array in Q12?

In [75]:
np.linalg.det(Arr1)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [79]:
print('5th Percentile Of Arr1:', np.percentile(Arr1, 5))
print('95th Percentile of Arr1:', np.percentile(Arr1, 95))

5th Percentile Of Arr1: 0.75
95th Percentile of Arr1: 14.25


## Question:15

### How to find if a given array has any null values?

In [90]:
Arr = np.arange(16)
print(Arr, '\n=======================\n', np.isnan(Arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] 
 [False False False False False False False False False False False False
 False False False False]
