# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [8]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [10]:
vector.shape

(40,)

5. Print the type of the previous array in question 3

In [11]:
vector.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [12]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

7. Print the dimension of the array in question 3


In [13]:
vector.ndim

1

8. Create a boolean array with all the True values

In [17]:
np.full((5), True)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [21]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [33]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [37]:
x = np.arange(20)
x[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [39]:
x1 = np.zeros(10)
x1[5] = 1
x1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [43]:
d2 = np.identity(3)
d2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [46]:
arr = np.array([1,2,3,4,5], dtype=float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [48]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])
arr3 = arr1*arr2
arr3

array([[ 0,  8,  3],
       [28, 10, 72]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [49]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
np.greater(arr1, arr2)

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [50]:
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [53]:
a[a % 2 == 1] = -1
a

array([-1,  2, -1,  4, -1,  6,  6, -1, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [59]:
arr = np.arange(10)
arr[5] = arr[6] = arr[7] = arr[8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [62]:
arr = np.ones((10,10))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [71]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [75]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr3d[0] =64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [84]:
arr2 = np.arange(10).reshape(2,5)
print(arr2)
print('^^^^^^^^^^Full Array^^^^^^^^^^^^^^')
print(arr2[0])
print('^^^^^^^^^^Slicing^^^^^^^^^^^')

[[0 1 2 3 4]
 [5 6 7 8 9]]
^^^^^^^^^^Full Array^^^^^^^^^^^^^^
[0 1 2 3 4]
^^^^^^^^^^Slicing^^^^^^^^^^^


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [88]:
arr2d = np.arange(10).reshape(2,5)
print(arr2d)
print('==============')
arr2d[1][1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [92]:
aar2d = np.arange(10).reshape(2,5)
print(arr2d)
arr2d[0:2,2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [109]:
arrd = np.empty(100).reshape(10,10)
print(arrd)
print('================')
print('Maximum',arrd.max())
print('================')
print('Minimum',arrd.min())

[[1.68064817e+00 2.74558510e-01 2.55486671e-01 3.58079040e-01
  1.45620726e+00 1.72893857e-01 2.20184306e+00 8.85977299e-01
  5.87662662e-01 6.28564707e-01]
 [2.73361152e-01 1.45582351e+00 7.03692918e-01 1.52041669e+00
  1.27556581e+00 1.52891892e+00 6.80205080e-01 6.00709599e-01
  8.45883636e-01 1.01564059e-01]
 [7.41142604e-01 7.26637718e-01 6.85056911e-01 1.03970937e+00
  9.08779022e-01 3.27314291e-01 1.93887487e+00 2.52840410e-02
  8.81363510e-04 1.02316125e-01]
 [4.99405778e-01 4.78544119e-01 1.22141316e+00 3.91505163e-01
  1.35093438e+00 9.92216454e-02 5.83059492e-01 4.53967667e-01
  2.40999227e-01 9.62862781e-01]
 [2.12490178e+00 2.41335406e-01 1.41037297e+00 5.36798512e-01
  7.79089425e-01 6.06772616e-01 3.45945196e-01 1.58439871e-01
  1.97431050e+00 3.31115467e-01]
 [5.06830188e-01 4.85122702e-01 5.95974268e-01 1.34142529e+00
  2.11477611e+00 6.06543394e-01 1.12715038e+00 1.18356862e+00
  4.05907475e-01 8.65156019e-01]
 [2.34094093e-01 1.61240389e+00 1.27820933e+00 1.06140215e

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [110]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [111]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [125]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

data = np.random.randn(7, 4)
data = data.astype(np.int64)
x = np.where(names[data] != 'Will')
x

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5,
        5, 6, 6, 6, 6], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 0, 1, 2,
        3, 0, 1, 2, 3], dtype=int64))

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [127]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

data = np.random.randn(7, 4)
data = data.astype(np.int64)
x = np.where((names[data] != 'Will') & (names[data] !='will'))
x

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
        6, 6, 6, 6], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 3, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3,
        0, 1, 2, 3], dtype=int64))

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [134]:
arr2d = np.random.uniform(low=1.0, high=15.0, size=(5,3))
arr2d

array([[ 4.33970538, 10.00816677, 11.61927539],
       [10.16354532, 11.78413202, 10.08510952],
       [ 3.81712721,  9.60054041, 13.47919616],
       [ 6.44060252, 12.09916724,  5.50941561],
       [ 9.85378312,  6.901624  , 13.0837309 ]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [136]:
ard = np.random.uniform(low=1.0, high=16.0, size=(2,2,4))
ard

array([[[ 5.20185675,  7.8108702 ,  9.47602218,  1.704129  ],
        [15.26226704,  9.31356874, 15.15239469,  4.22155566]],

       [[ 8.92430414, 14.91008994, 13.8729172 , 14.21276552],
        [11.43173642,  7.55472641, 14.75447538,  9.54504284]]])

33. Swap axes of the array you created in Question 32

In [140]:
np.swapaxes(ard, 0,2)

array([[[ 5.20185675,  8.92430414],
        [15.26226704, 11.43173642]],

       [[ 7.8108702 , 14.91008994],
        [ 9.31356874,  7.55472641]],

       [[ 9.47602218, 13.8729172 ],
        [15.15239469, 14.75447538]],

       [[ 1.704129  , 14.21276552],
        [ 4.22155566,  9.54504284]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [147]:
arr = np.arange(10)
print('Array of ten: ',arr)
sqrt = np.sqrt(arr)
print('Square Root Of Array: ',sqrt)
sqrt[sqrt < 0.5] = 0
sqrt

Array of ten:  [0 1 2 3 4 5 6 7 8 9]
Square Root Of Array:  [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

[8 6]
[]


<ipython-input-156-5b0011bf71f3>:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.where(arr1 == arr2)


(array([], dtype=int64),)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [157]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [159]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a,b)
result

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [166]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

sampleArray = np.delete(sampleArray, 1 , axis= 1)
newColumn = np.array([[10,10,10]])
sampleArray = np.insert(sampleArray, 1, newColumn, axis= 1)
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [167]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
a = x.dot(y)
a

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [168]:
x = np.random.randn(20)
x.cumsum()

array([-0.52287949, -0.24485999, -0.70864922,  0.00674571,  0.2698739 ,
        1.50348463,  1.74408081,  1.67534801,  2.19608889,  3.15514146,
        1.73883304,  1.51583998,  2.64444121,  2.29354535,  0.3364489 ,
        2.35392269,  1.03763962,  0.13535101,  0.5611231 , -0.76230571])